services:
  - type: web
    name: learning_log
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_default_superuser"
    startCommand: "gunicorn learning_log.wsgi:application"